env:
  global:
  - secure: "sEd5Lc6iZHvsDs8H+OWYF4wm08JHgtf5xdO4vhjUmHLMZQePFXBj0r739Zf7HtGESdepyYqtV+m4+ylwSGh36hIChgADh6gprtG8eLSjrnQfCbOSvTQpsJV+/4DNI6gF3Om9ELREavoll/Zi6SVbETKZWbgEmOGewQdU7jcgQ+lwhOnSSEoKgRTIihaotwCYM2bDXvW/0ErCANx3Vm+X2C2d47ChAMjPm18oBHvA2Dc78goWFN9DucXFWFfNiNZZqKeKwu6NuV+W8pUnfGr3qQSFqxdl4kfFkccNtWR99BZ/Xss+KAfM4NgH8lQAfS1m2Z8KJRUQq4tyNaqABqkW9wTswLSlS1oaGaUChC7+etliVNR4O+CJu67XWubAze99uKTHgcQk3zLbham4Od3i+oA7ShYSpi204jiYe4rLL+DSwfWplvD1/5TWWSchIFvLF5FapbAeKMyTsAPZAzM3aJS8DqER588Pni81FvpjnooBTDw4JJmJMdTO94fs8X56HLs4EcwIYwKkS1L0daEq8J7bBnwUv6vWxFA9oTlooWh798WwPu+NoV0K3KmQjy5r7dBzJ3qoicHFCuRRxbGpvqTixs/v/12uatmuu5XVCuo/tIhtqIl342nXYthjb4WZAhyhy7wkHUxjDpDeMLidbWxcZBGZb4oBkFGa3O4X4c0="
branches:
  only:
  - master
  - develop
script:
- /bin/true
after_success:
- make travisci-after-success
