class {"base":}
class {"selenium":}
class {"php5":}
class {"user-selenior":}
class {"nodejs":}
class {"composer":}
class {"bower":}
class {"simplecd":}
class {"cronjobs":}
class {"postfix":}
class {"nginx":}
