---
# The following are used in certain Puppet manifests, but never in app environments
# A parameter name starts with the name of the module that uses it
spark-slave::master_address: &spark_master_address 127.0.0.1
cassandra::cluster_name: JourneyMonitorProd
cassandra::seed_nodes: 127.0.0.1
cassandra::listen_interface: eth0
cassandra::rpc_address: 0.0.0.0
# Overwrite the following in host definitions, or else Spark will try to create connections
# to 127.0.0.1:9042, because after the initial connection the driver program thinks that
# this is the place to reach C*
cassandra::broadcast_rpc_address: 127.0.0.1
app-analyze::cassandra_cqlsh_host: &cassandra_cqlsh_host 127.0.0.1
app-analyze::spark_master_address: *spark_master_address
app-analyze::endpoint_monitor_api: &endpoint_monitor_api http://journeymonitor-monitor:8081/
app-analyze::endpoint_control_api: &endpoint_control_api http://journeymonitor-control:8082/
app-monitor::api:allowed_ips:
  - 127.0.0.1
cronjobs::endpoint_monitor_api: *endpoint_monitor_api
cronjobs::endpoint_control_api: *endpoint_control_api
cronjobs::endpoint_analyze_api: &endpoint_analyze_api "http://127.0.0.1:%{hiera('env::app-analyze:api:listen_port')}/"

# The following are used in app environments (see env-mgmt module), but never in Puppet manifests
env::cassandra:cqlsh_host: *cassandra_cqlsh_host
env::cassandra:host: *cassandra_cqlsh_host
env::cassandra:uri:analyze_keyspace: cassandra://127.0.0.1:9042/analyze
env::cassandra:uri:test_keyspace: cassandra://127.0.0.1:9042/test
env::endpoint:monitor_api: *endpoint_monitor_api
env::endpoint:analyze_api: *endpoint_analyze_api
env::app-analyze:api:listen_port: "8082"
# User journeymonitor can't write to /var/run, thus we write the pid to /var/tmp
env::app-analyze:api:pidfile_path: /var/tmp/journeymonitor-analyze-api.pid
env::app-control:sqlite:path: /var/tmp/journeymonitor-control-test.sqlite3
