#!/bin/bash

# managed by puppet

# Startet den per Parameter übergebenen Testcase und gibt das Ergebnis Nagios-kompatibel zurück

cd /var/tmp
RESULT=`/usr/bin/python2.7 /opt/websitetest/testcases/$1.py 2>&1`
STATUS=$?

if [ $STATUS -eq 2 ]; then
  echo "WEBSITETEST FAILURE - running '/usr/bin/python2.7 /opt/websitetest/testcases/$1.py 2>&1' failed."
  exit 3
fi

echo "$RESULT" | while IFS= read -r line;do echo "$(date) $line";done >> /opt/websitetest/log/testcase.$1.log

TIME=`echo "$RESULT" | grep "Ran " | grep "test in" | cut -d " " -f 5`

if [ $STATUS -eq 1 ]; then
  echo "WEBSITETEST CRITICAL - Failures occured. Test took $TIME to complete|time=$TIME;;;0,failure=1;;;0;1"
  exit 2
else
  echo "WEBSITETEST OK - Test took $TIME to complete|time=$TIME;;;0,failure=0;;;0;1"
  exit 0
fi
